server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  profiles:
    active: ${PROFILES}
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
    kubernetes:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    service-registry:
      enabled: true
logging:
  level:
    org:
      springframework: debug